version: "3.9"

volumes:
  db-data:

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - next-app
      - graphql-api
  next-app:
    container_name: "next-app-container"
    image: "next-app-image:v0.1.0"
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    tty: true
    working_dir: /app
    command: yarn dev
  graphql-api:
    container_name: "graphql-api-container"
    image: "graphql-api-image:v0.1.0"
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
      - '5555:5555'
    volumes:
      - ./api:/api
      - /api/node_modules
    tty: true
    working_dir: /api
    command: yarn start:dev
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgresql-container
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password




